name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      id: docker-build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: elixirdemo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Update Chart Version
      uses: jacobtomlinson/gha-find-replace@v2
      if: success() && steps.docker-build.outcome == 'success'
      with:
        find: "appVersion:.*"
        replace: "appVersion: '${{ github.sha }}'"
        include: "kubernetes/helm/Chart.yaml" # Will match all README.md files in any nested directory
        regex: true
    - name: Commit Chart Version Update
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: '.'
        author_name: GitHub Actions Workflow
        cwd: '.'
        default_author: github_actor
        pathspec_error_handling: ignore
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: '[skip actions] Commit from GitHub Actions. Updating Helm Chart AppVersion.'
